AllCops:
        NewCops: enable
        SuggestExtensions: false
        Exclude:
                - './bin/**/*'
                - './config/**/*'
                - './db/**/*'
                - './app/admin/**/*'
                - './vendor/**/*'
                - 'Guardfile'
                - 'Gemfile.lock'
Style/Documentation:
        Enabled: false
Metrics/BlockLength:
        Exclude:
                - './spec/**/*'
                - './app/models/state_machine/**/*'
Metrics/MethodLength:
        Max: 15
Style/RedundantFetchBlock:
        Enabled: false
